### ISSUE TITLE
Add a property to an AppUser entity

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#10]
### Description:
Adress property will be added to the appuser entity for address, city, county registration.

### Tasks:
- [x] Added `Appuser` entity Address property.
- [x] Added `Appuser` entity City property.
- [x] Added `Appuser` entity County property.
