### ISSUE TITLE
Add Log Entity

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#15]
### Description:
Entity will be created to save log information to the database.

### Tasks:
- [x] Added `Log` entity Id property.
- [x] Added `Log` entity TimeStamp property.
- [x] Added `Log` entity Level property.
- [x] Added `Log` entity Logger property.
- [x] Added `Log` entity Message property.
- [x] Added `Log` entity Exception property.
