### ISSUE TITLE
Implementing Product Management (CRUD) API Endpoints

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#2]
### Description:
API endpoints will be created for Product management. Users will be able to create, view, update, will be able to filter by category, and delete products.

The operations will be performed through the following endpoints:

- **POST /Product**: Create a new product
- **GET /Product**: List all products
- **GET /Product/{id}**: View a specific product
- **GET /Product/Filter/{id}**: List products by category
- **PUT /Product/{id}**: Update a product
- **DELETE /Product/{id}**: Delete a product

### Tasks:
- [x] Implement `POST /Product` endpoint.
- [x] Implement `GET /Product` endpoint.
- [x] Implement `GET /Product/{id}` endpoint.
- [x] Implement `GET /Product/Filter/{id}` endpoint.
- [x] Implement `PUT /Product/{id}` endpoint.
- [x] Implement `DELETE /Product/{id}` endpoint.
