### ISSUE TITLE
Implementing Role Management (CRUD) API Endpoints

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#3]
### Description:
Role CRUD operations, assigning a role to a user and deleting a role from a user will be performed.

The operations will be performed through the following endpoints:

- **POST /Role**: Create a new role
- **GET /Role**: List all roles
- **PUT /Role/{id}**: Update a role
- **DELETE /Role/{id}**: Delete a role
- **POST /Role/AddToRole/{userId}/{roleId}**: Add role to user
- **DELETE /Role/RemoveToRole/{userId}/{roleId}**: Remove the role in the user

### Tasks:
- [x] Implement `POST /Role` endpoint.
- [x] Implement `GET /Role` endpoint.
- [x] Implement `PUT /Role/{id}` endpoint.
- [x] Implement `DELETE /Role/{id}` endpoint.
- [x] Implement `POST /Role/AddToRole/{userId}/{roleId}` endpoint.
- [x] Implement `DELETE /Role/RemoveToRole/{userId}/{roleId}` endpoint.
