### ISSUE TITLE
Implementing User Management (CRUD) API Endpoints

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#4]
### Description:
User CRUD operations will be performed.

The operations will be performed through the following endpoints:

- **POST /User**: Create a new user
- **GET /User**: List all users
- **GET /User/{id}**: View a specific user
- **PUT /User/{id}**: Update a user
- **DELETE /User/{id}**: Delete a user

### Tasks:
- [x] Implement `POST /User` endpoint.
- [x] Implement `GET /User` endpoint.
- [x] Implement `GET /User/{id}` endpoint.
- [x] Implement `PUT /User/{id}` endpoint.
- [x] Implement `DELETE /User/{id}` endpoint.
