### ISSUE TITLE
Implementing Basket Management API Endpoints

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#5]
### Description:
Basket create, read, delete and basket items create, read, delete, quantity update operations will be performed.

The operations will be performed through the following endpoints:

- **POST /Basket**: Create a new basket and basket item will not be created if the basket exists
- **GET /Basket /{userId}**: View a specific basket
- **DELETE /Basket /{id}**: Delete a basket

### Tasks:
- [x] Implement `POST /Basket ` endpoint.
- [x] Implement `GET /Basket /{id}` endpoint.
- [x] Implement `DELETE /Basket /{id}` endpoint.
