### ISSUE TITLE
Implementing Order Management API Endpoints

### ISSUE THREAD

**Issue by SemihKaraagacli** [SemihKaraagacli/EcomPulse#6]
### Description:
Order create, read, delete operations will be performed.

The operations will be performed through the following endpoints:

- **POST /Order**: Create a new order
- **GET /Order**: List all orders
- **GET /Order/OrderId{orderId}**: View a specific order
- **DELETE /Order/{id}**: Delete a order

### Tasks:
- [x] Implement `POST /Order` endpoint.
- [x] Implement `GET /Order` endpoint.
- [x] Implement `GET /Order/OrderId{orderId}` endpoint.
- [x] Implement `DELETE /Order/{id}` endpoint.
